; ==========================================================
; Polybar Color Theme: dracula
; Dracula palette with semi-transparent background
; ==========================================================

[colors]
background = #99282A36
background-alt = #CC44475A
foreground = #F8F8F2
foreground-alt = #E2E2DC
primary = #BD93F9
secondary = #8BE9FD
accent = #FF79C6
success = #50FA7B
warning = #F1FA8C
alert = #FF5555
disabled = #6272A4
